version: "3.8"

services:
  #---------------------------------------------------------------------------------------------------------------------
  # The Server... responsible for mapping all http traffic to the necessary containers...
  #---------------------------------------------------------------------------------------------------------------------
  #
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - internal
    volumes:
      - ./server/sites-enabled:/etc/nginx/conf.d
      - ./websites:/var/www/html
    depends_on:
      - php
#      - js
      - database

  #---------------------------------------------------------------------------------------------------------------------
  # The Language Processor.
  #---------------------------------------------------------------------------------------------------------------------
  #
  php:
    container_name: php
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - internal
    volumes:
      - ./websites:/var/www/html

  #---------------------------------------------------------------------------------------------------------------------
  # JavaScript driven setups (not quite gonna work as intended)
  #---------------------------------------------------------------------------------------------------------------------
  #
  #js:
  #  container_name: js
  #  build:
  #    context: ./js
  #    dockerfile: Dockerfile
  #  ports:
  #    - "3000:3000"
  #  networks:
  #    - internal
  #  volumes:
  #    - ./websites:/var/www/html

  #---------------------------------------------------------------------------------------------------------------------
  # Event Handling... SOCKETS BAYBEEE TODO: (Rename this more appropriately)
  #---------------------------------------------------------------------------------------------------------------------
  #
  event:
    container_name: event
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_EXTRA_DIRECTIVES: |-
        cors_origins *
    ports:
      - "8000:80"
    networks:
      - internal
    volumes:
      - "./events/data:/data"
      - "./events/config:/config"

  #---------------------------------------------------------------------------------------------------------------------
  # The Database
  #---------------------------------------------------------------------------------------------------------------------
  #
  database:
    container_name: database
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    networks:
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database/data:/var/lib/mysql # persisting the data (when the docker containers are destroyed maintain data)

#-----------------------------------------------------------------------------------------------------------------------
# The Networks of the Docker environment.
#-----------------------------------------------------------------------------------------------------------------------
#
networks:
  internal:
    driver: bridge