version: "3.8"

services:

  #---------------------------------------------------------------------------------------------------------------------
  # The Server...
  #---------------------------------------------------------------------------------------------------------------------
  #
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "80:80"
    networks:
      - internal
    volumes:
      - ./server/sites-enabled:/etc/nginx/conf.d
      - ./websites:/var/www/html
    depends_on:
      - php
      - database

  #---------------------------------------------------------------------------------------------------------------------
  # The Language Processor.
  #---------------------------------------------------------------------------------------------------------------------
  #
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php
    ports:
      - "9000:9000"
    networks:
      - internal
    volumes:
      - ./websites:/var/www/html

  #---------------------------------------------------------------------------------------------------------------------
  # The Database
  #---------------------------------------------------------------------------------------------------------------------
  #
  database:
    image: mysql:5.7.22
    container_name: database
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    networks:
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database/data:/var/lib/mysql # persisting the data (when the docker containers are destroyed maintain data)

#-----------------------------------------------------------------------------------------------------------------------
# The Networks of the Docker environment.
#-----------------------------------------------------------------------------------------------------------------------
#
networks:
  internal:
    driver: bridge