#!/bin/bash

#-----------------------------------------------------------------------------------------------------------------------
# Script Intro...
#-----------------------------------------------------------------------------------------------------------------------
#
# Intro to this particular script
# This script is designed to make it easier for just setting up the necessary boilerplate stuff that each and every
# website is going to need... rather than going to each individual location and adding the necessary configurations it
# can be consolidated into this particular helper; which is going to take care of the following:
# adding the host into the hosts /etc/hosts file
# adding the necessary server configuration file into nginx where the website is going to be run from
# adding the necessary file and folder structure to the correct appropriate place (for this particular environment)
# so that you can immediately just hop to creating your website easily.
#
# This particular method *needs* right now to be ran as sudo (as it touches /etc/hosts).

#-----------------------------------------------------------------------------------------------------------------------
# Script Variables
#-----------------------------------------------------------------------------------------------------------------------
#
# The variables in which the script will be needing in order to fully process, here will be some defaults set in case
# the developer doesn't pass any in however $action will NEED to be passed to the script otherwise the whole script
# will just error.
# variables:
#   $action  -> (string) -> create|remove -> decide whether you are creating or removing a website
#   $website -> (string) -> the name of the website that the developer is going to be want making.
#   $user    -> (string) -> {user}:{user}|{user} -> to give necessary permissions to the files that are being generated.
#   $with    -> (string) -> composer,npm -> comma separated list that will tell the script what the developer is
#                           going to create. package.json, composer.json etc...
#   $host    -> (string) -> defaulted to 127.0.0.1 (localhost) -> the host in which the website will be served on.
#   $tld     -> (string) -> defaulted to test however enables the user any extension that they may desire.
#   $php     -> (string) -> defaulted to 8.2 however the developer will be able to pass one in (however... the container
#                           will also need updating (./docker-compose.yml). - this doesn't actually do anything as of
#                           the moment, which just simply specifies the PHP version inside the composer.json file if
#                           the user decides that they're making a project with composer.

action=$1;
website="";
user=$SUDO_USER;
with="";
host="127.0.0.1";
tld="test";
php="8.2";
database="";

for arg in "${@}"; do
    # if an argument has been passed with website. specified then we're going to extract the value of which comes after
    # and then assign it to the website that will be the name of the website that will be created later in the script.
    if [[ "$arg" == *"--website:"* ]]; then
        website=${arg/"--website:"/""};
    fi

    # If an argument has been passed with "with" then we're going to extract all the values that come after and apply to
    # the variable $with so that we can check later in the script what will want making. such as
    # composer.json/package.json etc...
    if [[ "$arg" == *"--with:"* ]]; then
        with=${arg/"--with:"/""};
    fi

    # If an argument has been passed with user, then this will be passed into the user variable, this variable is the
    # variable that is controlling who the permissions of the generated files will belong to. if this variable does not
    # get passed however; this will simply be the user that had called sudo. $SUDO_USER by default.
    if [[ "$arg" == *"--user:"* ]]; then
        user=${arg/"--user:"/""};
    fi

    # If an argument has been passed with the host, then we're going to extract the data of which comes after the host
    # and then assign it to the host variable, this will be where the websites are going to be hosted and what server...
    # i.e.. 127.0.0.1, 192.168.0.1, 0.0.0.0 etc.
    if [[ "$arg" == *"--host:"* ]]; then
        host=${arg/"--host:"/""};
    fi

    # If an argument has been passed with the tld (top level domain) then we're going to extract the data from
    # everything after tld: and assign it to the variable, which would be either .com, .org, .net, .test; etc...
    if [[ "$arg" == *"--tld:"* ]]; then
        tld=${arg/"--tld:"/""};
    fi

    # If an argument has been passed with the PHP version then we're going to extract it from the argument and apply
    # it to the variable (overriding the default php 8.2)...
    if [[ "$arg" == *"--php:"* ]]; then
        php={arg/"--php:"/""};
    fi

    if [[ "$arg" == *"--database:"* ]]; then
        database={arg/"--database:"/""};
    fi
done

#-----------------------------------------------------------------------------------------------------------------------
# Script Validations...
#-----------------------------------------------------------------------------------------------------------------------
#
# Here we are going to be checking whether the script is possible to run or not, checking the necessary variables have
# been handed to the script... if not then this will need to bomb the script out to avoid errors.

if [ -z "$action" ]; then
    echo "An action is required for this script to run, please provide action i.e... ./factory create|remove ...";
    exit;
fi

# if we hadn't passed in an action, "create" or "remove" then we can simply return early from this script; there would
# be nothing to really do at this point so close the script.
if [ "$action" != "create" ] && [ "$action" != "remove" ]; then
    echo "first passed parameter (action) wants to be [create|remove]";
    exit;
fi

# if the website hadn't been passed through then again, we're going to want to return out of this script early there
# would be no point executing this script when there's no website name to make.
if [ "$website" == "" ]; then
    echo "A website is needed to be passed in order for this script to work, i.e... ./factory create --website:test";
    exit;
fi

#-----------------------------------------------------------------------------------------------------------------------
# Server Template...
#-----------------------------------------------------------------------------------------------------------------------
#
# boilerplate content for the necessary website that's being created. This would be appended into
# ./server/sites-enabled/*.conf; which will enable the developer to then start accessing the domain without having to
# visit localhost

read -r -d '' server <<- EOL
server {
    listen 0.0.0.0:80;
    server_name $website.test www.$website.test;
    root /var/www/html/$website/public;
    index index.php index.html;

    location ~ \.php$ {
        try_files \$uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        fastcgi_param PATH_INFO \$fastcgi_path_info;
    }

    location / {
        try_files \$uri \$uri/ /index.php?\$query_string;
        gzip_static on;
    }
}
EOL

#-----------------------------------------------------------------------------------------------------------------------
# Website Template...
#-----------------------------------------------------------------------------------------------------------------------
#
# Boilerplate for your website, this is just a basic html snippet appended into the index.php file which would then
# allow the developer to begin working on the website with ease.

read -r -d '' web_index <<- EOL
<!DOCTYPE html>
<html lang="EN">
    <head>
        <title>$website</title>
        <style>
            html,
            html body {
                padding: 0;
                margin: 0;
                background-color: #181818;
            }

            body {
                height: 100vh;
                width: 100%;
                display: flex;
                align-items: center;
                justify-content: center;
                font-family: ProximaNova,
                             -apple-system,
                             BlinkMacSystemFont,
                             "Segoe UI",
                             Roboto,
                             "Helvetica Neue",
                             Arial,
                             sans-serif
            }

            body > div {
                text-align: center;
            }

            h1 {
                color: #ffffff;
            }

            h1 span {
                color: #ffa500;
            }

            p {
                color: rgba(255,255,255,0.75);
            }
        </style>
    </head>
    <body>
        <div>
            <h1>Welcome to <span>$website</span></h1>
            <p>This is your boilerplate website, feel free to modify it as you see fit.</p>
        </div>
    </body>
</html>
EOL

#-----------------------------------------------------------------------------------------------------------------------
# Composer Template...
#-----------------------------------------------------------------------------------------------------------------------
#
# Boilerplate for the composer.json file that will be included with the project if the script has specified that this
# is going to be wanted. if it is then this will be transferred across and composer install will be initiated from the
# docker-compose exec php container.

read -r -d '' composer <<- EOL
{
    "name": "$website/$website",
    "description": "$website made by the factory... fil in your at your own discretion",
    "type": "project",
    "license": "mit",
    "autoload": {
        "psr-4": {
            "${website^^}\\\\\\\\": "src/"
        }
    },
    "authors": [
        {
            "name": "First Last",
            "email": "first.last@provider.com"
        }
    ],
    "require": {
        "php": ">=$php"
    }
}
EOL

#-----------------------------------------------------------------------------------------------------------------------
# Create Utilities...
#-----------------------------------------------------------------------------------------------------------------------

# Utility method for handling updating the hosts file of the system, which would need to point localhost to the name of
# the website that we've just created. so the developer would then be able to navigate to website.extension on their
# system.
handle_create_hosts() {
    while IFS= read -r line; do
        if [[ "$line" == *"$website"* ]]; then
            echo "step 1: /etc/hosts already includes entry for $website moving on...";
            return;
        fi
    done <<< $(cat "/etc/hosts");
    echo "$host $website.$tld www.$website.$tld # -> from factory" >> /etc/hosts;
    echo "step 1: /etc/hosts has been updated to accommodate $website onto $host";
}

# Utility method for handling the creation of the website's configuration file, which will be created and dropped
# within the sites enabled within the server... at the current moment of development this would strictly be for a
# php/html based implementation devoid of proxies for frontend application development. however that might be something
# to consider when running this application -> appending some boilerplate proxy reverses for a frontend stack instead.
handle_create_configuration() {
    if [ ! -f "./container/server/sites-enabled/$website.conf" ]; then
        echo -e "$server" >> "./container/server/sites-enabled/${website}.conf";
        echo "step 2: $website.conf has been created within ./container/server/sites-enabled/$website.conf";
        return;
    fi
    echo "step 2: $website.conf already existed within ./container/server/sites-enabled/$website.conf";
}

# Utility method for handling the creation of the website, when hitting this part; within the environment we are going
# to generate the necessary boilerplate for the website; this particular snippet is going to check if that particular
# website already exists, so it doesn't get made twice, or doesn't happen to overwrite or append to what might already
# be there.
# todo - This particular method is also going to want to check whether there has been a symbolic link made for the
#        particular website also.
handle_create_website_creation() {
    if [ ! -d "./websites/$website" ]; then
        mkdir "./websites/$website";
    fi
    if [ ! -d "./website/$website/public" ]; then
        mkdir "./websites/$website/public";
    fi
    if [ ! -f "./websites/$website/public/index.php" ]; then
        echo -e "$web_index" >> "./websites/$website/public/index.php";
    fi
    echo "step 3: $website has been generated within ./websites/$website/public/";
}

# Utility method for handling the creation of the composer side, if the script had been executed with the composer being
# included, then we're going to need to set up the necessary composer files and auto-loading directories. upon this
# happening, we're then going to want to run the necessary container's directory composer install so that the files
# will be generated and auto-loading will be in place from the minute the user opens the web page.
handle_create_composer() {
    if [[ "$with" != *"composer"* ]]; then
        return;
    fi

    if [ ! -d "./websites/$website/src" ]; then
        mkdir "./websites/$website/src";
    fi

    # if the composer.json file already exists within the application then we're just going to want to do nothing and
    # exit on out of this particular piece.
    if [ ! -f "./websites/$website/composer.json" ]; then
        echo "step 3.1 composer.json has been added to ./websites/$website";
        echo -e "$composer" >> "./websites/$website/composer.json";
    else
        echo "Step 3.1 composer.json already exists";
    fi

    docker-compose run -w "/var/www/html/$website" php composer install;
    echo "step 3.2 composer has finished installing project";
}

# Utility method for handling the creation of a database; if the developer had specified the argument --database then
# what was passed will be the name of the database;
handle_create_database() {
    if [[ "$database" == "" ]]; then
        return;
    fi

    docker-compose exec "database mysql -uroot -proot -e "CREATE DATABASE $database"";
}

# Utility for handling the permissions to set the user for the one that the person specifies for within the command...
# if the user passes one that is, if they do not this will bomb out and do nothing. (Given the fact that this command
# may be ran as sudo, the directories and files are going to be created with the user "root" and the permissions for
# files will be non modifiable... thus will need transferring ownership or alerting the user that the ownership is set
# to a particular setting).
handle_permissions() {
    if [ ! -z "$user" ]; then
        chown -R $user:$user "./websites/$website";
        echo "step 4: Ownership of the files have been given to the user: [$user:$user] in [./websites/$website]";
        return;
    fi
    echo "step 4: No user specified, ownership will be given to [root:root] in [./websites/$website]";
}

#-----------------------------------------------------------------------------------------------------------------------
# Remove Utilities...
#-----------------------------------------------------------------------------------------------------------------------

# Utility method for the removal of the particular websites from the hosts file - this particular snippet would require
# the use of sudo. find all examples of the passed parameter "www.website.test" which is absolute to what the website
# would be called within the hosts file, which will limit the potential of having another similarly named website being
# stripped from the hosts file...
handle_remove_hosts() {
    sed -i "/www.$website.test/d" "/etc/hosts";
    echo "$website has been removed from the /etc/hosts; $website will no longer be accessible.";
}

# Utility method for the removal of the configuration files that reside within ./server/sites-enabled and contains the
# website.conf. This would be needed in order for the removal of the particular configuration on the nginx server so
# the page will no longer be available.
handle_remove_website_config() {
    if [ -f "./server/sites-enabled/$website.conf" ]; then
        rm "./server/sites-enabled/$website.conf";
        echo "$website.conf has been removed from ./server/sites-enabled";
        return;
    fi
    echo "$website.conf does not exist within ./server/sites-enabled";
}

# Utility method which will remove the website from the ./websites directory, cleaning up the space that that particular
# website might have taken up.
handle_remove_website_directory() {
    if [ -d "./websites/$website" ]; then
        rm -r "./websites/$website";
        echo "$website has been removed from ./websites";
        return;
    fi
    echo "$website does not exist within ./websites";
}

#-----------------------------------------------------------------------------------------------------------------------
# Run The Script...
#-----------------------------------------------------------------------------------------------------------------------

# if the user has said that the action is to create then we're going to want to run the necessary scripts to create the
# particular website.
if [ "$action" == "create" ]; then
    handle_create_hosts;
    handle_create_configuration;
    handle_create_website_creation;
    handle_create_composer;
    handle_permissions;
    handle_create_database;
fi

# if passing the action as remove then the script is going to start running the necessary methods in order to tear down
# the particular website that the developer will have passed.
if [ "$action" == "remove" ]; then
    handle_remove_hosts;
    handle_remove_website_config;
    handle_remove_website_directory;
fi

# After all the above had been ran and the new website is ready to be worked on, we can then restart the nginx process
# so that the new website can be immediately accessed without having to perform any rebuild.
docker-compose exec server nginx -s reload
